spring:
  application:
    name: postgres-bucket4j
  datasource:
    url: jdbc:postgres://localhost:5432/ratelimitdb
    driver-class-name: org.postgres.Driver
    username: myuser
    password: mypassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
